name: skincraft master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: skincraft-master
    steps:
      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CICD_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: cicd
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_ACCESS_KEY }}
          role-duration-seconds: 1200     
      - uses: actions/checkout@v3
        id: checkout
      # Upload the app on S3 bucket
      - name: Deploy app build to S3 bucket
        id: deploy
        run: aws s3 sync . s3://${{ secrets.BUCKET }} --cache-control "max-age=120000" --delete
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.SKINCRAFT_DISTRIBUTION_ID }}
          PATHS: "/index.html"